### PR TITLE
2 inc 5312 missing image

### PR DESCRIPTION
**Pull request by drewms**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
idk

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks drewms, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by drewms — COMMENTED** [review]
Solution unknown

**Review by drewms — COMMENTED** [review]
**

**Comment by vanessa-cooper** [comment]
@drewms I don't want to stress you out, but we really need you to finish this PR :)

**Pull request closed without merging**
